spring:
  application:
    name: gateway
server:
  port: 8080

zuul:
  routes:
    books:
      serviceId: books
      retryable: true
      path: /books/**
  ratelimit:
    repository: JPA
    enabled: true
    policy-list:
      books:
        - limit: 10
          refresh-interval: 30
          type:
            - user

ribbon:
  OkToRetryOnAllOperations: false
  eureka:
    enable: false

books:
  ribbon:
    listOfServers: http://localhost:8090,http://localhost:9090 #configure different hosts for load balancing
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 4
    retryableStatusCodes: 502,503,504 # which statuses to retry